create table if not exists public.app_state_history (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  data jsonb not null,
  changed_by text,
  note text
);
